import type { ResolvedBuiltinTool } from "@shared/contracts";
import { ToolRiskCategory } from "@shared/contracts";

/**
 * Static stub list of builtin tools for the Electron main process.
 * When the real runtime services are wired in, replace this with the
 * actual builtin-tool-registry.ts implementation.
 */
const RESOLVED_BUILTIN_TOOLS: ResolvedBuiltinTool[] = [
  {
    id: "fs.list",
    name: "列出文件",
    description: "列出当前附加工作目录下的文件和子目录。",
    group: "fs",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: true,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "inherit",
  },
  {
    id: "fs.read",
    name: "读取文件",
    description: "读取当前附加工作目录下的文本文件。",
    group: "fs",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: true,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "inherit",
  },
  {
    id: "fs.search",
    name: "搜索文件",
    description: "在当前附加工作目录下搜索文本内容。",
    group: "fs",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: true,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "inherit",
  },
  {
    id: "fs.write",
    name: "写入文件",
    description: "向当前附加工作目录写入文本文件。",
    group: "fs",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: true,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "always-ask",
  },
  {
    id: "fs.edit",
    name: "编辑文件",
    description: "局部编辑文件内容，通过精确字符串替换修改文件的特定部分。",
    group: "fs",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: true,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "always-ask",
  },
  {
    id: "exec.command",
    name: "执行命令",
    description: "在当前会话工作目录中执行命令。",
    group: "exec",
    risk: ToolRiskCategory.Exec,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "always-ask",
  },
  {
    id: "git.status",
    name: "Git 状态",
    description: "查看仓库工作区状态。",
    group: "git",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "inherit",
  },
  {
    id: "git.diff",
    name: "Git 差异",
    description: "查看当前工作区的文件变更摘要。",
    group: "git",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "inherit",
  },
  {
    id: "git.log",
    name: "Git 日志",
    description: "查看最近的 Git 提交历史。",
    group: "git",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "inherit",
  },
  {
    id: "git.commit",
    name: "Git 提交",
    description: "暂存所有更改并创建 Git 提交。",
    group: "git",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "always-ask",
  },
  {
    id: "http.fetch",
    name: "获取网页",
    description: "发起 GET 请求并查看响应内容。",
    group: "http",
    risk: ToolRiskCategory.Network,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "always-ask",
  },
  {
    id: "web.search",
    name: "网络搜索",
    description: "使用搜索引擎查询信息并返回摘要结果。",
    group: "web",
    risk: ToolRiskCategory.Network,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "always-ask",
  },
  {
    id: "task.manage",
    name: "任务管理",
    description: "创建、更新或查看多步骤工作的任务列表。",
    group: "task",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "inherit",
  },
];

export function listBuiltinToolDefinitions(): ResolvedBuiltinTool[] {
  return RESOLVED_BUILTIN_TOOLS.map((t) => ({ ...t }));
}
