import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));

const app = readFileSync(join(root, "app.vue"), "utf8");
const home = readFileSync(join(root, "pages/index.vue"), "utf8");
const login = readFileSync(join(root, "pages/login.vue"), "utf8");
const hub = readFileSync(join(root, "pages/hub.vue"), "utf8");
const projects = readFileSync(join(root, "pages/projects/index.vue"), "utf8");
const projectDetailPath = join(root, "pages/projects/[id]/index.vue");
const projectDetail = existsSync(projectDetailPath) ? readFileSync(projectDetailPath, "utf8") : "";
const projectEditPath = join(root, "pages/projects/[id]/edit.vue");
const projectEdit = existsSync(projectEditPath) ? readFileSync(projectEditPath, "utf8") : "";
const skills = readFileSync(join(root, "pages/skills/index.vue"), "utf8");
const skillDetail = readFileSync(join(root, "pages/skills/[id].vue"), "utf8");
const mcp = readFileSync(join(root, "pages/mcp/index.vue"), "utf8");
const mcpPublishPage = readFileSync(join(root, "pages/mcp/publish.vue"), "utf8");
const consolePage = readFileSync(join(root, "pages/console.vue"), "utf8");
const treeNode = readFileSync(join(root, "components/skills/SkillTreeNode.vue"), "utf8");
const authMiddleware = readFileSync(join(root, "middleware/platform-auth.global.ts"), "utf8");
const layout = readFileSync(join(root, "layouts/default.vue"), "utf8");
const session = readFileSync(join(root, "composables/useCloudSession.ts"), "utf8");
const markdownUtil = readFileSync(join(root, "utils/render-safe-markdown.ts"), "utf8");
const cloudApi = readFileSync(join(root, "server/lib/cloud-api.ts"), "utf8");
const css = readFileSync(join(root, "assets/css/main.css"), "utf8");
const cloudWebUiGuidelinesPath = join(root, "../../docs/cloud-web-ui-guidelines.md");
const cloudWebUiGuidelines = existsSync(cloudWebUiGuidelinesPath)
  ? readFileSync(cloudWebUiGuidelinesPath, "utf8")
  : "";

assert.ok(existsSync(join(root, "layouts/default.vue")));
assert.ok(existsSync(join(root, "assets/css/main.css")));
assert.ok(existsSync(join(root, "middleware/platform-auth.global.ts")));
assert.ok(existsSync(join(root, "utils/render-safe-markdown.ts")));
assert.ok(existsSync(join(root, "pages/console.vue")));
assert.ok(existsSync(join(root, "pages/projects/index.vue")));
assert.ok(!existsSync(join(root, "pages/projects.vue")));
assert.ok(existsSync(projectDetailPath));
assert.ok(!existsSync(join(root, "pages/projects/[id].vue")));
assert.ok(existsSync(projectEditPath));
assert.ok(existsSync(join(root, "pages/skills/index.vue")));
assert.ok(existsSync(join(root, "pages/skills/[id].vue")));
assert.ok(existsSync(join(root, "pages/skills/publish.vue")));
assert.ok(existsSync(join(root, "pages/mcp/index.vue")));
assert.ok(existsSync(join(root, "pages/mcp/publish.vue")));
assert.ok(!existsSync(join(root, "pages/mcp.vue")));
assert.ok(existsSync(join(root, "components/skills/SkillTreeNode.vue")));
assert.ok(existsSync(join(root, "server/api/skills.get.ts")));
assert.ok(existsSync(join(root, "server/api/skills.post.ts")));
assert.ok(existsSync(join(root, "server/api/skills/[id].get.ts")));
assert.ok(existsSync(join(root, "server/api/skills/[id]/releases.post.ts")));
assert.ok(existsSync(join(root, "server/api/skills/[id].put.ts")));
assert.ok(existsSync(join(root, "server/api/mcp/items.get.ts")));
assert.ok(existsSync(join(root, "server/api/mcp/items/[id].get.ts")));
assert.ok(existsSync(join(root, "server/api/mcp/items.post.ts")));
assert.ok(existsSync(join(root, "server/api/mcp/items/[id]/releases.post.ts")));
assert.ok(existsSync(join(root, "server/api/mcp/releases/[releaseId]/manifest.get.ts")));
assert.ok(existsSync(join(root, "server/api/hub/items.get.ts")));
assert.ok(existsSync(join(root, "server/api/hub/items/[id].get.ts")));
assert.ok(!existsSync(join(root, "server/api/hub/items/[id]/skill-releases.post.ts")));
assert.ok(existsSync(join(root, "server/api/hub/items/[id]/employee-releases.post.ts")));
assert.ok(existsSync(join(root, "server/api/hub/items/[id]/workflow-releases.post.ts")));
assert.ok(!existsSync(join(root, "server/api/hub/items/skills.post.ts")));
assert.ok(existsSync(join(root, "server/api/hub/releases/[releaseId]/manifest.get.ts")));
assert.ok(existsSync(join(root, "server/api/hub/releases/[releaseId]/download-token.get.ts")));
assert.ok(existsSync(join(root, "server/api/projects.get.ts")));
assert.ok(existsSync(join(root, "server/api/projects.post.ts")));
assert.ok(existsSync(join(root, "server/api/projects/[id].get.ts")));
assert.ok(existsSync(join(root, "server/api/projects/[id]/config.put.ts")));
assert.ok(existsSync(join(root, "server/api/auth/login.post.ts")));
assert.ok(existsSync(join(root, "server/api/auth/introspect.post.ts")));
assert.ok(existsSync(cloudWebUiGuidelinesPath));

assert.match(app, /NuxtLayout/);

assert.match(home, /navigateTo/);
assert.match(home, /\/login/);
assert.match(home, /replace:\s*true/);

assert.match(authMiddleware, /defineNuxtRouteMiddleware/);
assert.match(authMiddleware, /\/login/);
assert.match(authMiddleware, /\/hub/);
assert.match(authMiddleware, /\/console/);
assert.match(authMiddleware, /clearSession/);

assert.match(layout, /useCloudSession/);
assert.match(layout, /MyClaw Cloud/);
assert.match(layout, /to:\s*"\/projects"/);
assert.match(layout, /to:\s*"\/skills"/);
assert.match(layout, /to:\s*"\/mcp"/);
assert.match(layout, /handleLogout/);
assert.match(layout, /theme-toggle/);
assert.match(layout, /user-chip-nx/);

assert.match(session, /useCookie/);
assert.match(session, /myclaw-cloud-session/);
assert.match(session, /isSessionValid/);
assert.match(session, /sessionExpiresAt/);
assert.doesNotMatch(session, /localStorage/);
assert.doesNotMatch(session, /window\.addEventListener/);
assert.doesNotMatch(session, /payload\.refreshToken/);

assert.match(markdownUtil, /renderSafeMarkdown/);
assert.match(markdownUtil, /escapeHtml/);

assert.match(cloudApi, /getCookie/);
assert.match(cloudApi, /myclaw-cloud-session/);
assert.match(cloudApi, /Bearer/);

assert.match(login, /redirect/);
assert.match(login, /navigateTo/);
assert.match(login, /\/api\/auth\/login/);
assert.match(login, /handleLogin/);
assert.match(login, /redirectTarget/);
assert.match(login, /MyClaw Cloud/);
assert.match(login, /showPassword/);
assert.match(login, /login-shell/);
assert.match(login, /login-hero/);
assert.match(login, /@media\s*\(max-width:\s*900px\)/);
assert.match(login, /overflow:\s*hidden/);
assert.match(login, /position:\s*fixed/);
assert.match(login, /minmax\(360px,\s*460px\)/);
assert.doesNotMatch(login, /hero-grid/);
assert.doesNotMatch(login, /hero-note/);

assert.match(hub, /\/api\/hub\/items/);
assert.match(hub, /\/api\/projects/);
assert.match(hub, /to="\/projects"/);
assert.match(hub, /debouncedKeyword/);
assert.match(hub, /setTimeout/);
assert.match(hub, /\/api\/hub\/releases\/\$\{releaseId\}\/download-token/);
assert.match(hub, /handleDownloadRelease/);
assert.match(hub, /selectedItemId/);
assert.match(hub, /云端资源总览/);
assert.match(hub, /统一查看 MCP、员工包、工作流包和项目接入/);
assert.match(hub, /搜索 Hub 资源/);
assert.match(hub, /全部/);
assert.match(hub, /员工包/);
assert.match(hub, /工作流包/);
assert.match(hub, /项目接入/);
assert.match(hub, /项目/);
assert.match(hub, /正在加载资源列表/);
assert.match(hub, /正在加载详情/);
assert.match(hub, /下载失败，请稍后重试。/);
assert.match(hub, /选择左侧资源查看详细信息。/);
assert.match(hub, /下载/);
assert.doesNotMatch(hub, /type === "skill"/);
assert.doesNotMatch(hub, /['"]skill['"]/);
assert.doesNotMatch(hub, /route\.query\.create/);
assert.doesNotMatch(hub, /openCreateSkillPanel/);

assert.match(projects, /\/api\/projects/);
assert.match(projects, /openCreateProject/);
assert.match(projects, /handleSaveProject/);
assert.match(projects, /新建后进入项目详情，再编辑仓库、接口、Skills 和 MCP/);
assert.match(projects, /method:\s*"POST"/);
assert.match(projects, /新建项目/);
assert.match(projects, /项目维护/);
assert.match(projects, /NuxtLink/);
assert.match(projects, /`\/projects\/\$\{project\.id\}`/);
assert.match(projects, /card-action-nx/);
assert.match(projects, /查看详情/);
assert.doesNotMatch(projects, /selectedProjectId/);
assert.doesNotMatch(projects, /selectProject/);
assert.doesNotMatch(projects, /openEditProject/);
assert.doesNotMatch(projects, /project-detail-panel/);
assert.doesNotMatch(projects, /正在加载项目详情/);
assert.doesNotMatch(projects, /选择项目卡片查看维护配置/);
assert.doesNotMatch(projects, /method:\s*"PUT"/);

assert.match(projectDetail, /route\.params\.id/);
assert.match(projectDetail, /\/api\/projects\/\$\{projectId\.value\}/);
assert.match(projectDetail, /project-detail:\$\{projectId\.value\}/);
assert.doesNotMatch(projectDetail, /project:\$\{projectId\.value\}/);
assert.match(projectDetail, /`\/projects\/\$\{projectId\}\/edit`/);
assert.doesNotMatch(projectDetail, /openEditProject/);
assert.doesNotMatch(projectDetail, /formMode/);
assert.match(projectDetail, /handleSaveProjectConfig/);
assert.match(projectDetail, /<Teleport to="body">/);
assert.match(projectDetail, /role="dialog"/);
assert.match(projectDetail, /editor-modal/);
assert.match(projectDetail, /method:\s*"PUT"/);
assert.match(projectDetail, /function openProjectConfigAddModal/);
assert.match(projectDetail, /function openProjectConfigEditModal/);
assert.match(projectDetail, /function confirmProjectConfigModal/);
assert.match(projectDetail, /function buildReplaceProjectPayload/);
assert.match(projectDetail, /\/api\/skills/);
assert.match(projectDetail, /\/api\/mcp\/items/);
assert.match(projectDetail, /编辑项目/);
assert.match(projectDetail, /project-detail-panel/);
assert.match(projectDetail, /JSON/);
assert.match(projectDetail, /服务端点/);
assert.match(projectDetail, /selectedProject\.services/);
assert.match(projectDetail, /displayServiceBaseUrl/);
assert.match(projectDetail, /resource-table resource-table--repositories/);
assert.match(projectDetail, /resource-table resource-table--services/);
assert.match(projectDetail, /resource-table resource-table--apis/);
assert.match(projectDetail, /resource-table resource-table--skills/);
assert.match(projectDetail, /resource-table resource-table--mcps/);
assert.match(projectDetail, /resource-actions/);
assert.match(projectDetail, /openProjectConfigAddModal\('service'\)/);
assert.match(projectDetail, /openProjectConfigAddModal\('repository'\)/);
assert.match(projectDetail, /openProjectConfigAddModal\('api'\)/);
assert.match(projectDetail, /openProjectConfigAddModal\('skill'\)/);
assert.match(projectDetail, /openProjectConfigAddModal\('mcp'\)/);
assert.match(projectDetail, /ProjectApiRequestBodyType/);
assert.match(projectDetail, /API_BODY_TYPE_OPTIONS/);
assert.match(projectDetail, /parametersText/);
assert.match(projectDetail, /requestBodyType/);
assert.match(projectDetail, /requestBodyContentType/);
assert.match(projectDetail, /requestBodyExampleText/);
assert.match(projectDetail, /formatApiRequestConfig/);
assert.match(projectDetail, /v-model="addModalDraft\.api\.parametersText"/);
assert.match(projectDetail, /v-model="addModalDraft\.api\.requestBodyType"/);
assert.match(projectDetail, /v-model="addModalDraft\.api\.requestBodyContentType"/);
assert.match(projectDetail, /v-model="addModalDraft\.api\.requestBodyExampleText"/);
assert.match(projectDetail, /openProjectConfigEditModal\('service'/);
assert.match(projectDetail, /openProjectConfigEditModal\('repository'/);
assert.match(projectDetail, /openProjectConfigEditModal\('api'/);
assert.match(projectDetail, /openProjectConfigEditModal\('skill'/);
assert.match(projectDetail, /openProjectConfigEditModal\('mcp'/);
assert.doesNotMatch(projectDetail, /\?add=service/);
assert.doesNotMatch(projectDetail, /\?add=repository/);
assert.match(projectDetail, /新增仓库/);
assert.doesNotMatch(projectDetail, /\?add=api/);
assert.match(projectDetail, /新增接口/);
assert.doesNotMatch(projectDetail, /\?add=skill/);
assert.match(projectDetail, /新增 Skill/);
assert.doesNotMatch(projectDetail, /\?add=mcp/);
assert.match(projectDetail, /新增 MCP/);
assert.doesNotMatch(projectDetail, /detail-card-grid/);
assert.doesNotMatch(projectDetail, /repositoriesText/);
assert.doesNotMatch(projectDetail, /apisText/);
assert.doesNotMatch(projectDetail, /skillsText/);
assert.doesNotMatch(projectDetail, /mcpsText/);

assert.match(projectEdit, /route\.params\.id/);
assert.match(projectEdit, /\/api\/projects\/\$\{projectId\.value\}/);
assert.match(projectEdit, /project-edit:\$\{projectId\.value\}/);
assert.doesNotMatch(projectEdit, /project:\$\{projectId\.value\}/);
assert.match(projectEdit, /handleSaveProject/);
assert.match(projectEdit, /method:\s*"PUT"/);
assert.match(projectEdit, /编辑项目/);
assert.match(projectEdit, /\/api\/skills/);
assert.match(projectEdit, /\/api\/mcp\/items/);
assert.match(projectEdit, /projectForm\.repositories/);
assert.match(projectEdit, /projectForm\.services/);
assert.match(projectEdit, /projectForm\.apis/);
assert.match(projectEdit, /projectForm\.skills/);
assert.match(projectEdit, /projectForm\.mcps/);
assert.match(projectEdit, /ProjectServiceFormItem/);
assert.match(projectEdit, /function createServiceFormItem/);
assert.match(projectEdit, /function buildServicePayload/);
assert.match(projectEdit, /services: buildServicePayload\(\)/);
assert.match(projectEdit, /服务端点/);
assert.match(projectEdit, /Base URL/);
assert.match(projectEdit, /route\.query\.add/);
assert.match(projectEdit, /consumeAddActionFromRoute/);
assert.match(projectEdit, /function createEmptyProjectForm/);
assert.match(projectEdit, /function syncProjectForm/);
assert.match(projectEdit, /function createServiceFormItem/);
assert.match(projectEdit, /function createRepositoryFormItem/);
assert.match(projectEdit, /function createApiFormItem/);
assert.match(projectEdit, /function createSkillFormItem/);
assert.match(projectEdit, /function createMcpFormItem/);
assert.match(projectEdit, /<section id="services" class="editor-section">\s*<div class="section-toolbar">\s*<div>\s*<h3>服务端点<\/h3>/);
assert.match(projectEdit, /<section id="repositories" class="editor-section">\s*<div class="section-toolbar">\s*<div>\s*<h3>代码仓库<\/h3>/);
assert.match(projectEdit, /<section id="apis" class="editor-section">\s*<div class="section-toolbar">\s*<div>\s*<h3>接口<\/h3>/);
assert.match(projectEdit, /<section id="skills" class="editor-section">\s*<div class="section-toolbar">\s*<div>\s*<h3>Skills<\/h3>/);
assert.match(projectEdit, /<section id="mcps" class="editor-section">\s*<div class="section-toolbar">\s*<div>\s*<h3>MCP<\/h3>/);
assert.match(projectEdit, /addRepository/);
assert.match(projectEdit, /addService/);
assert.match(projectEdit, /addApi/);
assert.match(projectEdit, /addSkillRef/);
assert.match(projectEdit, /addMcpRef/);
assert.match(projectEdit, /function openProjectConfigAddModal/);
assert.match(projectEdit, /function closeProjectConfigAddModal/);
assert.match(projectEdit, /function confirmProjectConfigAddModal/);
assert.match(projectEdit, /projectConfigModalMode/);
assert.match(projectEdit, /editingConfigFormKey/);
assert.match(projectEdit, /function openProjectConfigEditModal/);
assert.match(projectEdit, /function seedProjectConfigEditModalDraft/);
assert.match(projectEdit, /function applyProjectConfigEditModalDraft/);
assert.match(projectEdit, /function confirmProjectConfigDelete/);
assert.match(projectEdit, /activeAddModalAction/);
assert.match(projectEdit, /ProjectConfigAddModalDraft/);
assert.doesNotMatch(projectEdit, /hash:\s*route\.hash/);
assert.doesNotMatch(projectEdit, /hash:\s*`#\$\{anchor\}`/);
assert.match(projectEdit, /API_METHOD_OPTIONS/);
assert.match(projectEdit, /ProjectApiRequestBodyType/);
assert.match(projectEdit, /API_BODY_TYPE_OPTIONS/);
assert.match(projectEdit, /parametersText/);
assert.match(projectEdit, /requestBodyType/);
assert.match(projectEdit, /requestBodyContentType/);
assert.match(projectEdit, /requestBodyExampleText/);
assert.match(projectEdit, /v-model="addModalDraft\.api\.method"/);
assert.match(projectEdit, /v-model="addModalDraft\.api\.serviceName"/);
assert.match(projectEdit, /v-model="addModalDraft\.api\.parametersText"/);
assert.match(projectEdit, /v-model="addModalDraft\.api\.requestBodyType"/);
assert.match(projectEdit, /v-model="addModalDraft\.api\.requestBodyContentType"/);
assert.match(projectEdit, /v-model="addModalDraft\.api\.requestBodyExampleText"/);
assert.doesNotMatch(projectEdit, /<select v-model="api\.method">/);
assert.doesNotMatch(projectEdit, /<select v-model="api\.serviceName">/);
assert.doesNotMatch(projectEdit, /v-model="api\.owner"/);
assert.match(projectEdit, /<Teleport to="body">/);
assert.match(projectEdit, /role="dialog"/);
assert.match(projectEdit, /config-table config-table--services/);
assert.match(projectEdit, /config-table config-table--repositories/);
assert.match(projectEdit, /config-table config-table--apis/);
assert.match(projectEdit, /config-table config-table--skills/);
assert.match(projectEdit, /config-table config-table--mcps/);
assert.match(projectEdit, /config-row-actions/);
assert.match(projectEdit, /icon-action/);
assert.match(projectEdit, /openProjectConfigAddModal\('service'\)/);
assert.match(projectEdit, /openProjectConfigAddModal\('repository'\)/);
assert.match(projectEdit, /openProjectConfigAddModal\('api'\)/);
assert.match(projectEdit, /openProjectConfigAddModal\('skill'\)/);
assert.match(projectEdit, /openProjectConfigAddModal\('mcp'\)/);
assert.match(projectEdit, /openProjectConfigEditModal\('service'/);
assert.match(projectEdit, /openProjectConfigEditModal\('repository'/);
assert.match(projectEdit, /openProjectConfigEditModal\('api'/);
assert.match(projectEdit, /openProjectConfigEditModal\('skill'/);
assert.match(projectEdit, /openProjectConfigEditModal\('mcp'/);
assert.doesNotMatch(projectEdit, /@click="addRepository"/);
assert.doesNotMatch(projectEdit, /@click="addApi"/);
assert.doesNotMatch(projectEdit, /@click="addSkillRef"/);
assert.doesNotMatch(projectEdit, /@click="addMcpRef"/);
assert.doesNotMatch(projectEdit, /class="editor-card/);
assert.doesNotMatch(projectEdit, /每个仓库都是独立卡片/);
assert.match(projectEdit, /`\/projects\/\$\{projectId\}`/);
assert.match(projectEdit, /editor-modal/);
assert.match(projects, /Skills/);
assert.match(projects, /MCP/);
assert.match(projectDetail, /代码仓库/);
assert.match(projectDetail, /融智链项目/);
assert.match(projectDetail, /接口/);
assert.match(projectDetail, /Skills/);
assert.match(projectDetail, /MCP/);
assert.match(projectDetail, /工作流 \/ 硅基员工/);
assert.match(projectDetail, /预留维护位/);

assert.match(cloudWebUiGuidelines, /列表页不内嵌右侧详情预览/);
assert.match(cloudWebUiGuidelines, /列表卡片只保留查看详情/);
assert.match(cloudWebUiGuidelines, /编辑入口只放在详情页/);
assert.match(cloudWebUiGuidelines, /已保存的仓库、服务端点、接口、Skill、MCP 必须默认呈现为紧凑行/);
assert.match(cloudWebUiGuidelines, /添加任意服务端点、接口、Skill 或 MCP 后，页面中出现的是一行新资源摘要/);

assert.match(skills, /\/api\/skills/);
assert.match(skills, /debouncedKeyword/);
assert.match(skills, /setTimeout/);
assert.match(skills, /NuxtLink/);
assert.match(skills, /card-action-nx/);
assert.match(skills, /list-action-nx/);
assert.match(skills, /glass-card-nx/);
assert.doesNotMatch(skills, /\.skill-card-nx::before/);
assert.doesNotMatch(skills, /\/api\/hub\//);
assert.match(skills, /\/skills\/publish/);
assert.doesNotMatch(skills, /local skills/i);
assert.match(skills, /搜索 Skills/);
assert.match(skills, /发布 Skill/);
assert.match(skills, /个 Skills/);
assert.match(skills, /正在加载 Skills 列表/);
assert.match(skills, /没有找到匹配的 Skills/);

assert.match(skillDetail, /route\.params\.id/);
assert.match(skillDetail, /renderSafeMarkdown/);
assert.match(skillDetail, /\/api\/skills\/\$\{skillId\.value\}/);
assert.doesNotMatch(skillDetail, /buildSkillTree/);
assert.doesNotMatch(skillDetail, /selectedFile/);
assert.doesNotMatch(skillDetail, /Browse local/i);

const publishPage = readFileSync(join(root, "pages/skills/publish.vue"), "utf8");
const skillsPost = readFileSync(join(root, "server/api/skills.post.ts"), "utf8");

assert.match(publishPage, /\/api\/skills/);
assert.match(publishPage, /handlePublish/);
assert.doesNotMatch(publishPage, /\/api\/hub\//);
assert.match(publishPage, /FormData/);
assert.match(publishPage, /type="file"/);
assert.match(publishPage, /accept="\.zip"/);
assert.match(publishPage, /返回 Skills/);
assert.match(publishPage, /发布 Skill/);
assert.match(publishPage, /上传 Skill 包/);
assert.match(publishPage, /选择 ZIP/);
assert.match(publishPage, /选择文件夹/);
assert.match(publishPage, /webkitdirectory/);
assert.match(publishPage, /renderSafeMarkdown/);
assert.match(publishPage, /v-html="renderedSkillMarkdown"/);
assert.match(publishPage, /Markdown 预览/);
assert.match(publishPage, /解析 Skill 元数据/);
assert.match(publishPage, /请先上传包含 SKILL\.md 的 Skill 包/);
assert.match(publishPage, /发布技能失败/);
assert.match(publishPage, /已有版本/);
assert.match(publishPage, /本次发布版本/);
assert.match(publishPage, /v-model="releaseVersion"/);
assert.match(publishPage, /resolveNextPatchVersion/);
assert.match(publishPage, /existingSkill\.value\?\.latestVersion/);
assert.match(publishPage, /formData\.append\("files"/);
assert.match(publishPage, /formData\.append\("file"/);
assert.match(publishPage, /formData\.append\("version", releaseVersion\.value/);
assert.match(publishPage, /parseSkillMarkdownMetadata/);
assert.match(publishPage, /extractSkillMarkdownFromZip/);
assert.doesNotMatch(publishPage, /<pre>{{ skillPreview\.readme }}<\/pre>/);
assert.doesNotMatch(publishPage, /chars/);
assert.doesNotMatch(publishPage, /v-model="form\.name"/);
assert.doesNotMatch(publishPage, /v-model="form\.summary"/);
assert.doesNotMatch(publishPage, /v-model="form\.description"/);
assert.doesNotMatch(publishPage, /v-model="form\.category"/);
assert.doesNotMatch(publishPage, /custom-select/);

assert.match(skillsPost, /proxyCloudApi/);
assert.doesNotMatch(skillsPost, /mkdirSync/);
assert.doesNotMatch(skillsPost, /writeFileSync/);

assert.match(treeNode, /tree-node/);
assert.match(treeNode, /node\.type === "file"/);
assert.match(treeNode, /emit\("select"/);

assert.match(mcp, /\/api\/mcp\/items/);
assert.match(mcp, /<button type="button" class="close-btn"/);
assert.doesNotMatch(mcp, /\/api\/hub\/items/);
assert.match(mcp, /selectedConnectorId/);
assert.match(mcp, /selectedManifest/);
assert.match(mcp, /transportOptions/);
assert.match(mcp, /selectedTransport/);
assert.match(mcp, /MCP 管理/);
assert.match(mcp, /创建 MCP/);
assert.match(mcp, /正在加载 MCP 列表/);
assert.match(mcp, /连接器/);
assert.match(mcp, /发布新版本/);
assert.match(mcp, /版本将由 Cloud 自动递增/);
assert.match(mcp, /连接配置清单/);
assert.match(mcp, /stdio/);
assert.match(mcp, /streamable-http/);
assert.match(mcp, /请选择左侧 MCP 查看配置/);
assert.doesNotMatch(mcp, /Register New MCP/);
assert.doesNotMatch(mcp, /accept="\.zip"/);
assert.doesNotMatch(mcp, /v-model="publishForm\.version"/);

assert.match(mcpPublishPage, /\/api\/mcp\/items/);
assert.match(mcpPublishPage, /CreateMcpItemResponse/);
assert.match(mcpPublishPage, /返回 MCP/);
assert.match(mcpPublishPage, /创建 MCP/);
assert.match(mcpPublishPage, /基础信息/);
assert.match(mcpPublishPage, /连接配置/);
assert.match(mcpPublishPage, /传输方式/);
assert.match(mcpPublishPage, /启动命令/);
assert.match(mcpPublishPage, /命令参数/);
assert.match(mcpPublishPage, /远程地址/);
assert.match(mcpPublishPage, /创建 MCP 失败/);
assert.match(mcpPublishPage, /版本将由 Cloud 自动递增/);
assert.doesNotMatch(mcpPublishPage, /accept="\.zip"/);
assert.doesNotMatch(mcpPublishPage, /FormData/);
assert.doesNotMatch(mcpPublishPage, /请先选择 ZIP 包后再创建/);
assert.doesNotMatch(mcpPublishPage, /v-model="form\.version"/);

const mcpPost = readFileSync(join(root, "server/api/mcp/items.post.ts"), "utf8");
const mcpReleasePost = readFileSync(join(root, "server/api/mcp/items/[id]/releases.post.ts"), "utf8");
assert.match(mcpPost, /readBody/);
assert.doesNotMatch(mcpPost, /readFormData/);
assert.match(mcpReleasePost, /readBody/);
assert.doesNotMatch(mcpReleasePost, /readFormData/);

assert.match(consolePage, /navigateTo/);
assert.match(consolePage, /\/hub/);
assert.match(consolePage, /replace:\s*true/);

assert.match(css, /skill-tree/);
assert.match(css, /file-viewer/);
assert.match(css, /auth-shell/);
assert.match(css, /user-chip/);

console.log("cloud-web pages verified");
