import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

const root = fileURLToPath(new URL("..", import.meta.url));

const indexSource = readFileSync(join(root, "src/index.ts"), "utf8");
const source = readFileSync(join(root, "src/contracts/hub.ts"), "utf8");
const skillsContractPath = join(root, "src/contracts/skills.ts");
const mcpContractPath = join(root, "src/contracts/mcp.ts");
const projectsContractPath = join(root, "src/contracts/projects.ts");

assert.ok(existsSync(skillsContractPath));
assert.ok(existsSync(mcpContractPath));
assert.ok(existsSync(projectsContractPath));
assert.match(indexSource, /contracts\/skills/);
assert.match(indexSource, /contracts\/mcp/);
assert.match(indexSource, /contracts\/projects/);

const skillsSource = readFileSync(skillsContractPath, "utf8");
const mcpSource = readFileSync(mcpContractPath, "utf8");
const projectsSource = readFileSync(projectsContractPath, "utf8");
assert.match(skillsSource, /export type SkillSummary/);
assert.match(skillsSource, /export type SkillDetail/);
assert.match(skillsSource, /export type CreateSkillInput/);
assert.match(skillsSource, /export type PublishSkillReleaseResponse/);
assert.match(skillsSource, /artifact:/);
assert.match(skillsSource, /sha256: string/);
assert.match(mcpSource, /export type McpItemSummary/);
assert.match(mcpSource, /export type McpItemDetail/);
assert.match(mcpSource, /export type CreateMcpItemInput/);
assert.match(mcpSource, /export type CreateMcpItemResponse/);
assert.match(mcpSource, /export type PublishMcpReleaseResponse/);
assert.match(mcpSource, /transport: "stdio"/);
assert.match(mcpSource, /transport: "sse"/);
assert.match(mcpSource, /transport: "streamable-http"/);
assert.match(projectsSource, /export type ProjectDetail/);
assert.match(projectsSource, /export type ProjectId = number/);
assert.match(projectsSource, /id: ProjectId/);
assert.match(projectsSource, /export type ProjectApiParameterLocation/);
assert.match(projectsSource, /export type ProjectApiRequestBodyType/);
assert.match(projectsSource, /export type ProjectApiParameterInfo/);
assert.match(projectsSource, /parametersJson: ProjectApiParameterInfo\[\] \| null/);
assert.match(projectsSource, /requestBodyType: ProjectApiRequestBodyType/);
assert.match(projectsSource, /requestBodyContentType: string \| null/);
assert.match(projectsSource, /requestBodyExampleJson: unknown/);
assert.match(projectsSource, /export type ProjectServiceInfo/);
assert.match(projectsSource, /services: ProjectServiceInfo\[\]/);
assert.match(projectsSource, /export type ProjectSummary = \{[\s\S]*?version: number/);
assert.match(projectsSource, /export type ProjectRuntimeContext/);
assert.match(projectsSource, /export type ProjectRuntimeSkill/);
assert.match(projectsSource, /export type ProjectRuntimeMcp/);
assert.match(projectsSource, /export type ProjectRuntimeWarning/);
assert.match(projectsSource, /export type CreateProjectInput/);
assert.match(projectsSource, /export type ProjectServiceInput/);
assert.match(projectsSource, /services\?: ProjectServiceInput\[\]/);
assert.match(projectsSource, /status\?: ProjectStatus/);
assert.match(projectsSource, /export type ReplaceProjectConfigInput/);
assert.match(projectsSource, /ProjectRepositoryType/);

assert.doesNotMatch(source, /"skill"/);
assert.match(source, /"mcp"/);
assert.match(source, /"employee-package"/);
assert.match(source, /"workflow-package"/);
assert.doesNotMatch(source, /SkillReleaseUploadResponse/);
assert.doesNotMatch(source, /CreateSkillItemInput/);
assert.doesNotMatch(source, /CreateSkillReleaseResponse/);
assert.match(source, /artifact:/);
assert.match(source, /sha256: string/);
assert.match(source, /HubManifest/);

console.log("shared contracts verified");
