import type { ResolvedBuiltinTool } from "@shared/contracts";
import { ToolRiskCategory } from "@shared/contracts";

/**
 * Static stub list of builtin tools for the Electron main process.
 * When the real runtime services are wired in, replace this with the
 * actual builtin-tool-registry.ts implementation.
 */
const RESOLVED_BUILTIN_TOOLS: ResolvedBuiltinTool[] = [
  {
    id: "fs.list",
    name: "列出文件",
    description: "列出当前附加工作目录下的文件和子目录。",
    group: "fs",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: true,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "inherit",
  },
  {
    id: "fs.read",
    name: "读取文件",
    description: "读取当前附加工作目录下的文本文件。",
    group: "fs",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: true,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "inherit",
  },
  {
    id: "fs.search",
    name: "搜索文件",
    description: "在当前附加工作目录下搜索文本内容。",
    group: "fs",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: true,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "inherit",
  },
  {
    id: "fs.write",
    name: "写入文件",
    description: "向当前附加工作目录写入文本文件。",
    group: "fs",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: true,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "always-ask",
  },
  {
    id: "fs.edit",
    name: "编辑文件",
    description: "局部编辑文件内容，通过精确字符串替换修改文件的特定部分。",
    group: "fs",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: true,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "always-ask",
  },
  {
    id: "exec.command",
    name: "执行命令",
    description: "在当前会话工作目录中执行命令。",
    group: "exec",
    risk: ToolRiskCategory.Exec,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "always-ask",
  },
  {
    id: "git.status",
    name: "Git 状态",
    description: "查看仓库工作区状态。",
    group: "git",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "inherit",
  },
  {
    id: "git.diff",
    name: "Git 差异",
    description: "查看当前工作区的文件变更摘要。",
    group: "git",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "inherit",
  },
  {
    id: "git.log",
    name: "Git 日志",
    description: "查看最近的 Git 提交历史。",
    group: "git",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "inherit",
  },
  {
    id: "git.commit",
    name: "Git 提交",
    description: "暂存所有更改并创建 Git 提交。",
    group: "git",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "always-ask",
  },
  {
    id: "http.fetch",
    name: "获取网页",
    description: "发起 GET 请求并查看响应内容。",
    group: "http",
    risk: ToolRiskCategory.Network,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "always-ask",
  },
  {
    id: "web.search",
    name: "网络搜索",
    description: "使用搜索引擎查询信息并返回摘要结果。",
    group: "web",
    risk: ToolRiskCategory.Network,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "always-ask",
  },
  // ── browser.* ── 浏览器自动化工具组 ──────────────────────
  {
    id: "browser.open",
    name: "打开网页",
    description: "在浏览器中打开指定 URL，自动启动系统 Chrome/Edge。",
    group: "browser",
    risk: ToolRiskCategory.Network,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "always-ask",
  },
  {
    id: "browser.snapshot",
    name: "页面快照",
    description: "获取当前页面的 accessibility tree 结构化快照。",
    group: "browser",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "inherit",
  },
  {
    id: "browser.click",
    name: "点击元素",
    description: "点击页面上的指定元素。",
    group: "browser",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "always-ask",
  },
  {
    id: "browser.type",
    name: "输入文本",
    description: "在输入框中键入文本。",
    group: "browser",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "always-ask",
  },
  {
    id: "browser.screenshot",
    name: "页面截图",
    description: "截取当前页面截图，返回 base64 编码的 PNG。",
    group: "browser",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "inherit",
  },
  {
    id: "browser.evaluate",
    name: "执行脚本",
    description: "在页面上下文执行 JavaScript 表达式。",
    group: "browser",
    risk: ToolRiskCategory.Exec,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "always-ask",
  },
  {
    id: "browser.select",
    name: "选择选项",
    description: "选择下拉框中的选项。",
    group: "browser",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "always-ask",
  },
  {
    id: "browser.hover",
    name: "悬停元素",
    description: "将鼠标悬停在指定元素上。",
    group: "browser",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "always-ask",
  },
  {
    id: "browser.back",
    name: "后退",
    description: "浏览器后退到上一页。",
    group: "browser",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "always-ask",
  },
  {
    id: "browser.forward",
    name: "前进",
    description: "浏览器前进到下一页。",
    group: "browser",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "always-ask",
  },
  {
    id: "browser.wait",
    name: "等待",
    description: "等待指定毫秒数，用于页面加载或动画。",
    group: "browser",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "inherit",
  },
  {
    id: "browser.scroll",
    name: "滚动页面",
    description: "滚动页面或指定元素，用于查看视口外内容。",
    group: "browser",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "inherit",
  },
  {
    id: "browser.press_key",
    name: "按键操作",
    description: "按下键盘按键或快捷键组合（如 Escape、Tab、Control+a）。",
    group: "browser",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "always-ask",
  },
  // ── ppt.* ── 演示文稿生成工具组 ──────────────────────
  {
    id: "ppt.themes",
    name: "PPT 主题列表",
    description: "获取所有可用的演示文稿主题及其配色预览。",
    group: "ppt",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "inherit",
  },
  {
    id: "ppt.generate",
    name: "生成 PPT",
    description: "根据结构化内容生成可编辑的 .pptx 演示文稿。",
    group: "ppt",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "always-ask",
  },
  {
    id: "reminder.create",
    name: "创建提醒",
    description: "在本地时间中心创建用户提醒。",
    group: "time",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "inherit",
  },
  {
    id: "reminder.list",
    name: "查看提醒",
    description: "查看本地时间中心中的提醒列表。",
    group: "time",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "inherit",
  },
  {
    id: "schedule_job.create",
    name: "创建定时任务",
    description: "创建本地定时执行任务。",
    group: "time",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "always-ask",
  },
  {
    id: "schedule_job.list",
    name: "查看定时任务",
    description: "查看本地时间中心中的定时任务列表。",
    group: "time",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "inherit",
  },
  {
    id: "today_brief.get",
    name: "今日摘要",
    description: "读取本地时间中心生成的今日摘要。",
    group: "time",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabled: true,
    exposedToModel: true,
    effectiveApprovalMode: "inherit",
  },
];

export function listBuiltinToolDefinitions(): ResolvedBuiltinTool[] {
  return RESOLVED_BUILTIN_TOOLS.map((t) => ({ ...t }));
}
