import type { BuiltinToolApprovalMode, BuiltinToolGroup, ResolvedBuiltinTool } from "@shared/contracts";
import { ToolRiskCategory } from "@shared/contracts";

export type BuiltinToolExposure = "active" | "legacy" | "hidden" | "disabled";

export type BuiltinToolRegistryEntry = {
  id: string;
  modelName: string;
  aliases: string[];
  name: string;
  description: string;
  group: BuiltinToolGroup;
  risk: ToolRiskCategory;
  requiresAttachedDirectory: boolean;
  enabledByDefault: boolean;
  exposedByDefault: boolean;
  approvalMode: BuiltinToolApprovalMode;
  exposure: BuiltinToolExposure;
};

const READ_APPROVAL: BuiltinToolApprovalMode = "inherit";
const WRITE_APPROVAL: BuiltinToolApprovalMode = "always-ask";

const BUILTIN_TOOL_REGISTRY: BuiltinToolRegistryEntry[] = [
  {
    id: "fs.read",
    modelName: "fs_read",
    aliases: [],
    name: "读取文件",
    description: "读取当前附加工作目录下的文本文件。",
    group: "fs",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: true,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "file.view",
    modelName: "file_view",
    aliases: [],
    name: "查看文件",
    description: "在右侧面板中预览本地文件，或调用系统默认应用打开文件；默认不把正文注入模型上下文。",
    group: "fs",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: true,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "xlsx.extract",
    modelName: "xlsx_extract",
    aliases: ["document.read"],
    name: "读取 Excel",
    description: "兼容保留的 Excel 读取入口，执行层应复用 document.read 的工作簿解析能力。",
    group: "fs",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: true,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "legacy",
  },
  {
    id: "document.read",
    modelName: "document_read",
    aliases: [],
    name: "读取文档",
    description: "读取 Office、PDF、Markdown、CSV、JSON 等文档并支持统计、目录、精确读取和搜索。",
    group: "fs",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: true,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "fs.write",
    modelName: "fs_write",
    aliases: [],
    name: "写入文件",
    description: "向当前附加工作目录写入文本文件。",
    group: "fs",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: true,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: WRITE_APPROVAL,
    exposure: "active",
  },
  {
    id: "fs.list",
    modelName: "fs_list",
    aliases: [],
    name: "列出文件",
    description: "列出当前附加工作目录下的文件和子目录。",
    group: "fs",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: true,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "fs.search",
    modelName: "fs_search",
    aliases: [],
    name: "搜索文件内容",
    description: "在当前附加工作目录下搜索文本内容。",
    group: "fs",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: true,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "fs.find",
    modelName: "fs_find",
    aliases: [],
    name: "查找文件",
    description: "在当前附加工作目录下按 glob 模式查找文件。",
    group: "fs",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: true,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "fs.edit",
    modelName: "fs_edit",
    aliases: [],
    name: "编辑文件",
    description: "局部编辑文件内容，通过精确字符串替换修改文件的特定部分。",
    group: "fs",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: true,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: WRITE_APPROVAL,
    exposure: "active",
  },
  {
    id: "artifact.register",
    modelName: "artifact_register",
    aliases: [],
    name: "登记工作文件",
    description: "将已经生成的本地文件登记到 Files 工作台，供会话文件列表、最近产出和右侧预览使用。",
    group: "fs",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: true,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: WRITE_APPROVAL,
    exposure: "active",
  },
  {
    id: "exec.command",
    modelName: "exec_command",
    aliases: [],
    name: "执行命令",
    description: "在当前会话工作目录中执行命令。",
    group: "exec",
    risk: ToolRiskCategory.Exec,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: WRITE_APPROVAL,
    exposure: "active",
  },
  {
    id: "git.status",
    modelName: "git_status",
    aliases: [],
    name: "Git 状态",
    description: "查看仓库工作区状态。",
    group: "git",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "git.diff",
    modelName: "git_diff",
    aliases: [],
    name: "Git 差异",
    description: "查看当前工作区的文件变更摘要。",
    group: "git",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "git.log",
    modelName: "git_log",
    aliases: [],
    name: "Git 日志",
    description: "查看最近的 Git 提交历史。",
    group: "git",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "git.commit",
    modelName: "git_commit",
    aliases: [],
    name: "Git 提交",
    description: "暂存所有更改并创建 Git 提交。",
    group: "git",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: WRITE_APPROVAL,
    exposure: "active",
  },
  {
    id: "http.fetch",
    modelName: "http_fetch",
    aliases: [],
    name: "获取网页",
    description: "发起 GET 请求并查看响应内容。",
    group: "http",
    risk: ToolRiskCategory.Network,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: WRITE_APPROVAL,
    exposure: "active",
  },
  {
    id: "web.search",
    modelName: "web_search",
    aliases: [],
    name: "网络搜索",
    description: "使用搜索引擎查询信息并返回摘要结果。",
    group: "web",
    risk: ToolRiskCategory.Network,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: WRITE_APPROVAL,
    exposure: "active",
  },
  {
    id: "ppt.themes",
    modelName: "ppt_themes",
    aliases: [],
    name: "PPT 主题列表",
    description: "获取所有可用的演示文稿主题及其配色预览。",
    group: "ppt",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "ppt.generate",
    modelName: "ppt_generate",
    aliases: [],
    name: "生成 PPT",
    description: "根据结构化内容生成可编辑的 .pptx 演示文稿。",
    group: "ppt",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: WRITE_APPROVAL,
    exposure: "active",
  },
  {
    id: "task.create",
    modelName: "task_create",
    aliases: [],
    name: "创建任务",
    description: "创建本地任务并写入任务中心。",
    group: "task",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "task.list",
    modelName: "task_list",
    aliases: [],
    name: "查看任务",
    description: "查看本地任务中心中的任务列表。",
    group: "task",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "task.get",
    modelName: "task_get",
    aliases: [],
    name: "读取任务",
    description: "读取本地任务中心中的单个任务。",
    group: "task",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "task.update",
    modelName: "task_update",
    aliases: [],
    name: "更新任务",
    description: "更新本地任务中心中的任务状态或内容。",
    group: "task",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "task.wait_for_user",
    modelName: "task_wait_for_user",
    aliases: [],
    name: "等待用户",
    description: "创建 Task V2 用户中断请求，并在本轮终止自动续跑。",
    group: "task",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "calendar_event.create",
    modelName: "calendar_event_create",
    aliases: [],
    name: "创建日程",
    description: "在本地时间中心创建会议、评审或固定时间段日程，可同步创建会前提醒。",
    group: "time",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "calendar_event.list",
    modelName: "calendar_event_list",
    aliases: [],
    name: "查看日程",
    description: "查看本地时间中心中的日程列表。",
    group: "time",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "reminder.create",
    modelName: "reminder_create",
    aliases: [],
    name: "创建提醒",
    description: "在本地时间中心创建用户提醒。",
    group: "time",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "reminder.list",
    modelName: "reminder_list",
    aliases: [],
    name: "查看提醒",
    description: "查看本地时间中心中的提醒列表。",
    group: "time",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "schedule_job.create",
    modelName: "schedule_job_create",
    aliases: [],
    name: "创建定时任务",
    description: "创建本地定时执行任务。",
    group: "time",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: WRITE_APPROVAL,
    exposure: "active",
  },
  {
    id: "schedule_job.list",
    modelName: "schedule_job_list",
    aliases: [],
    name: "查看定时任务",
    description: "查看本地时间中心中的定时任务列表。",
    group: "time",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "today_brief.get",
    modelName: "today_brief_get",
    aliases: [],
    name: "今日摘要",
    description: "读取本地时间中心生成的今日摘要。",
    group: "time",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "browser.open",
    modelName: "browser_open",
    aliases: [],
    name: "打开网页",
    description: "在浏览器中打开指定 URL，自动启动系统 Chrome/Edge。",
    group: "browser",
    risk: ToolRiskCategory.Network,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: WRITE_APPROVAL,
    exposure: "active",
  },
  {
    id: "browser.snapshot",
    modelName: "browser_snapshot",
    aliases: [],
    name: "页面快照",
    description: "获取当前页面的 accessibility tree 结构化快照。",
    group: "browser",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "browser.click",
    modelName: "browser_click",
    aliases: [],
    name: "点击元素",
    description: "点击页面上的指定元素。",
    group: "browser",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: WRITE_APPROVAL,
    exposure: "active",
  },
  {
    id: "browser.type",
    modelName: "browser_type",
    aliases: [],
    name: "输入文本",
    description: "在输入框中键入文本。",
    group: "browser",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: WRITE_APPROVAL,
    exposure: "active",
  },
  {
    id: "browser.screenshot",
    modelName: "browser_screenshot",
    aliases: [],
    name: "页面截图",
    description: "截取当前页面截图，返回本地图片路径。",
    group: "browser",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "browser.evaluate",
    modelName: "browser_evaluate",
    aliases: [],
    name: "执行脚本",
    description: "在页面上下文执行 JavaScript 表达式。",
    group: "browser",
    risk: ToolRiskCategory.Exec,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: WRITE_APPROVAL,
    exposure: "active",
  },
  {
    id: "browser.select",
    modelName: "browser_select",
    aliases: [],
    name: "选择选项",
    description: "选择下拉框中的选项。",
    group: "browser",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: WRITE_APPROVAL,
    exposure: "active",
  },
  {
    id: "browser.hover",
    modelName: "browser_hover",
    aliases: [],
    name: "悬停元素",
    description: "将鼠标悬停在指定元素上。",
    group: "browser",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: WRITE_APPROVAL,
    exposure: "active",
  },
  {
    id: "browser.back",
    modelName: "browser_back",
    aliases: [],
    name: "后退",
    description: "浏览器后退到上一页。",
    group: "browser",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: WRITE_APPROVAL,
    exposure: "active",
  },
  {
    id: "browser.forward",
    modelName: "browser_forward",
    aliases: [],
    name: "前进",
    description: "浏览器前进到下一页。",
    group: "browser",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: WRITE_APPROVAL,
    exposure: "active",
  },
  {
    id: "browser.wait",
    modelName: "browser_wait",
    aliases: [],
    name: "等待",
    description: "等待指定毫秒数，用于页面加载或动画。",
    group: "browser",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "browser.scroll",
    modelName: "browser_scroll",
    aliases: [],
    name: "滚动页面",
    description: "滚动页面或指定元素，用于查看视口外内容。",
    group: "browser",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
  {
    id: "browser.press_key",
    modelName: "browser_press_key",
    aliases: [],
    name: "按键操作",
    description: "按下键盘按键或快捷键组合。",
    group: "browser",
    risk: ToolRiskCategory.Write,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: WRITE_APPROVAL,
    exposure: "active",
  },
  {
    id: "skill.view",
    modelName: "skill_view",
    aliases: [],
    name: "打开 Skill 面板",
    description: "在具备 HTML 面板的 Skill 完成工作后打开可视化结果面板，支持直接传入数据或本地 dataRef。",
    group: "skill",
    risk: ToolRiskCategory.Read,
    requiresAttachedDirectory: false,
    enabledByDefault: true,
    exposedByDefault: true,
    approvalMode: READ_APPROVAL,
    exposure: "active",
  },
];

const BY_ID = new Map(BUILTIN_TOOL_REGISTRY.map((tool) => [tool.id, tool]));
const BY_MODEL_NAME = new Map(BUILTIN_TOOL_REGISTRY.map((tool) => [tool.modelName, tool]));
const BY_ALIAS = new Map(BUILTIN_TOOL_REGISTRY.flatMap((tool) => tool.aliases.map((alias) => [alias, tool] as const)));

/** 列出 builtin 工具注册表条目，供 schema、工具中心和测试共享同一事实来源。 */
export function listBuiltinToolRegistryEntries(): BuiltinToolRegistryEntry[] {
  return BUILTIN_TOOL_REGISTRY.map((tool) => ({ ...tool, aliases: [...tool.aliases] }));
}

/** 将注册表条目投影为工具中心使用的已解析 builtin 工具。 */
export function listBuiltinToolDefinitions(): ResolvedBuiltinTool[] {
  return BUILTIN_TOOL_REGISTRY.map((tool) => ({
    id: tool.id,
    name: tool.name,
    description: tool.description,
    group: tool.group,
    risk: tool.risk,
    requiresAttachedDirectory: tool.requiresAttachedDirectory,
    enabled: tool.enabledByDefault,
    exposedToModel: tool.exposedByDefault,
    effectiveApprovalMode: tool.approvalMode,
  }));
}

/** 根据模型函数名解析 builtin 工具条目，避免执行链路靠字符串替换猜测来源。 */
export function resolveBuiltinToolByFunctionName(functionName: string): BuiltinToolRegistryEntry | null {
  const tool = BY_MODEL_NAME.get(functionName) ?? BY_ID.get(functionName) ?? BY_ALIAS.get(functionName);
  return tool ? { ...tool, aliases: [...tool.aliases] } : null;
}

/** 根据 builtin 工具 ID 解析注册表条目。 */
export function resolveBuiltinToolById(toolId: string): BuiltinToolRegistryEntry | null {
  const tool = BY_ID.get(toolId);
  return tool ? { ...tool, aliases: [...tool.aliases] } : null;
}

/** 将 builtin 工具 ID 映射为模型函数名。 */
export function builtinToolIdToFunctionName(toolId: string): string | null {
  return BY_ID.get(toolId)?.modelName ?? null;
}

/** 推断 builtin 模型函数所属分组，供 provider 工具策略过滤复用。 */
export function inferBuiltinToolSchemaGroup(functionName: string): BuiltinToolGroup | null {
  return BY_MODEL_NAME.get(functionName)?.group ?? BY_ALIAS.get(functionName)?.group ?? null;
}
