/** 共享 desktop builtin tool 名单，避免多份测试基线漂移。 */
export const EXPECTED_BUILTIN_TOOL_NAMES = [
  "fs_read",
  "fs_write",
  "fs_list",
  "fs_search",
  "fs_find",
  "fs_edit",
  "exec_command",
  "git_status",
  "git_diff",
  "git_log",
  "git_commit",
  "http_fetch",
  "web_search",
  "ppt_themes",
  "ppt_generate",
  "task_create",
  "task_list",
  "task_get",
  "task_update",
  "browser_open",
  "browser_snapshot",
  "browser_click",
  "browser_type",
  "browser_screenshot",
  "browser_evaluate",
  "browser_select",
  "browser_hover",
  "browser_back",
  "browser_forward",
  "browser_wait",
  "browser_scroll",
  "browser_press_key",
] as const;
